services:
  redis:
    image: redis:7-alpine
    container_name: urban-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  urban-api-1:
    build: .
    container_name: urban-api-1
    depends_on:
      - redis
    restart: unless-stopped

  urban-api-2:
    build: .
    container_name: urban-api-2
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: urban-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - urban-api-1
      - urban-api-2
    restart: unless-stopped