events {}
http {
    upstream urban_backend {
        server urban-api-1:8000;
        server urban-api-2:8000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://urban_backend;
        }
    }
}
